### ISSUE TITLE
jQuery y Google Fonts deberian cargarse por SSL

### ISSUE THREAD

**Issue by laantorchaweb** [Aerolab/svg#1]
Gente, muy bueno el laburo que hacen, la parte de zoom no estaba andando y me di cuenta que Chrome estaba bloqueando jQuery por no estar usando https.

Habria que actualizar la url para jQuery y Google Fonts a usar https o simplemente usar `//` en las urls 

Saludos.

**Comment by RobertoGonzalez** [comment]
Buen catch! Corregido
